version: 2.1

orbs:
  codecov: codecov/codecov@1.0.5

workflows:
  version: 2
  test:
    jobs:
      - py27
      - py35
      - py36
      - py37
      - py38
      - py39
      - pypy
      - pypy3
      - black
      - check-manifest
      - docs
      - flake8

jobs:
  py39: &test-template
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          name: Install test dependencies
          command: sudo pip install tox || pip install tox
      - restore_cache:
          name: Restoring tox cache
          keys:
            - tox-v1-{{ .Environment.CIRCLE_JOB }}-{{ .BuildNum }}
            - tox-v1-{{ .Environment.CIRCLE_JOB }}
      - run:
          name: Run tests
          command: |
            tox -e $CIRCLE_JOB -- \
              --junit-xml=test-results/pytest/results.xml \
              --cov-report=xml
      - save_cache:
          name: Saving tox cache
          key: tox-v1-{{ .Environment.CIRCLE_JOB }}-{{ .BuildNum }}
          paths:
            - ./.tox
            - ~/.cache/pip
      - codecov/upload:
          file: coverage.xml
      - store_test_results:
          path: test-results

  py27:
    <<: *test-template
    docker:
      - image: circleci/python:2.7

  py35:
    <<: *test-template
    docker:
      - image: circleci/python:3.5

  py36:
    <<: *test-template
    docker:
      - image: circleci/python:3.6

  py37:
    <<: *test-template
    docker:
      - image: circleci/python:3.7

  py38:
    <<: *test-template
    docker:
      - image: circleci/python:3.8

  pypy:
    <<: *test-template
    docker:
      - image: pypy:2.7

  pypy3:
    <<: *test-template
    docker:
      - image: pypy:3.5

  black: *test-template

  check-manifest: *test-template

  docs: *test-template

  flake8: *test-template
